<a href="https://colab.research.google.com/github/Jeyandan2626/wkshop_data_engineer/blob/main/wkshop_dataeng_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
print("lib load completed "
)

df=pd.read_csv("student_performance.csv")
print(df)
df.head()
df.tail()

lib load completed
    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.head()
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df.shape

(30, 13)

In [ ]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [ ]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print(df["student_id"])

0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
15    1016
16    1017
17    1018
18    1019
19    1020
20    1021
21    1022
22    1023
23    1024
24    1025
25    1026
26    1027
27    1028
28    1029
29    1030
Name: student_id, dtype: int64

In [ ]:
df["department"].unique()

array(['Computer Science', 'Electronics', 'Mechanical', 'Civil'],
      dtype=object)

In [ ]:
df["department"].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
bu = df[df['department'] == 'Computer Science']

print(len(bu))

print(bu[['name', 'math_score', 'programming_score', 'attendance_percentage']])

13
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [ ]:
bu = df[df['attendance_percentage'] >= 90]

print(len(bu))
print(bu[['name', 'department', 'attendance_percentage']])

11
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
4       Arjun Nair  Computer Science                     90
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [ ]:
bu = df[(df['department'] == 'Computer Science') &
        (df['attendance_percentage'] >= 90)]

print(len(bu))
print(bu[['name', 'math_score', 'programming_score', 'attendance_percentage']])

8
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
17  Swati Kulkarni          90                 92                     94
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
29  Akanksha Yadav          91                 94                     95

In [ ]:
top = df[df['programming_score'] == df['programming_score'].max()]

print(top[['name', 'department', 'programming_score']])

         name        department  programming_score
9  Ananya Das  Computer Science                 97

In [ ]:
max_score = df.groupby('department')[[
    'math_score',
    'science_score',
    'english_score',
    'programming_score'
]].max()

print(max_score)

                  math_score  science_score  english_score  programming_score
department
Civil                     73             72             79                 44
Computer Science          95             93             90                 97
Electronics               87             83             86                 72
Mechanical                77             81             82                 53

In [ ]:
avg_score = df.groupby('department')[[
    'math_score',
    'science_score',
    'english_score',
    'programming_score'
]].mean()

print(avg_score)

                  math_score  science_score  english_score  programming_score
department
Civil              63.400000      66.600000      65.200000          40.600000
Computer Science   85.615385      84.461538      80.846154          89.230769
Electronics        71.000000      74.166667      70.833333          61.500000
Mechanical         71.000000      76.500000      70.500000          49.333333

In [ ]:
print("DataSet Overview")

print("Shape of dataset:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

DataSet Overview
Shape of dataset: (30, 13)

Column Names:
Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
dtypes: int64(9), object(4)
memory usage: 3.2+ KB
None

Statistical Summary:
        student_id        age  semester  math_score  science_score  \
count    30.000000  30.000000      30.0   30.000000      30.000000
mean   1015.500000  19.733333       2.0   76.066667      77.833333
std       8.803408   0.739680       0.0   11.467896       8.554423
min    1001.000000  19.000000       2.0   56.000000      61.000000
25%    1008.250000  19.000000       2.0   67.250000      71.250000
50%    1015.500000  20.000000       2.0   75.500000      78.000000
75%    1022.750000  20.000000       2.0   85.750000      83.750000
max    1030.000000  21.000000       2.0   95.000000      93.000000

       english_score  programming_score  attendance_percentage  admission_year
count      30.000000          30.000000              30.000000            30.0
mean       74.166667          67.600000              84.500000          2023.0
std        10.003735          21.041175               9.379913             0.0
min        55.000000          38.000000              65.000000          2023.0
25%        67.250000          49.250000              77.250000          2023.0
50%        75.000000          66.000000              86.500000          2023.0
75%        81.750000          88.750000              91.750000          2023.0
max        90.000000          97.000000              98.000000          2023.0

In [ ]:
dept_count = df['department'].value_counts()

print(dept_count)

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print("Maximum Scores:")
print(df[['math_score','science_score',
          'english_score','programming_score']].max())

print("\nMinimum Scores:")
print(df[['math_score','science_score',
          'english_score','programming_score']].min())

Maximum Scores:
math_score           95
science_score        93
english_score        90
programming_score    97
dtype: int64

Minimum Scores:
math_score           56
science_score        61
english_score        55
programming_score    38
dtype: int64

In [ ]:
print("Maximum Math Score :", df['math_score'].max())
print("Minimum Math Score :", df['math_score'].min())
print("Average Math Score :", df['math_score'].mean())
print("Average of programming score:", df['programming_score'].mean())
print("average attendance:", df['attendance_percentage'].mean())

Maximum Math Score : 95
Minimum Math Score : 56
Average Math Score : 76.06666666666666
Average of programming score: 67.6
average attendance: 84.5

In [ ]:
print("-"*40)
top5=df.sort_values("total_scores",aascending=False).head(5)

for index, row in top5.iterrows():
  print(f"{row['name']:<20}|{row['department']:<18}|score:{row['total_score']}"
  )

----------------------------------------

TypeError: DataFrame.sort_values() got an unexpected keyword argument 'aascending'